### ISSUE TITLE
syntax highlighting for enclosed comments

### ISSUE THREAD

**Issue by joachimheintz** [CsoundQt/CsoundQt#320]
the /* ... */ is good to comment out larger blocks of code.  but if small comments are included, the highlighting is out of order. try:

/*
doiu
//doiu
doiu
*/

**Comment by gesellkammer** [comment]
fixed in git

**Comment by eleses** [comment]
@gesellkammer  It's not entirely fixed, semicolon comments still screw it up.

<img width="94" height="84" alt="Image" src="https://github.com/user-attachments/assets/f2aedc5c-8099-4880-8bec-f93d4d6e2cf4" />

vs

<img width="84" height="79" alt="Image" src="https://github.com/user-attachments/assets/7c67b5a0-d4cc-4c1a-b47d-a3bbf350810e" />
